# 1. Learning Numpy Basics

In [1]:
import numpy as np

In [2]:
mylist= [1,2,3]

In [3]:
type(mylist)

list

In [4]:
myarray=np.array(mylist)

In [5]:
type(myarray)

numpy.ndarray

### Matrix

In [6]:
matrix= [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
np.zeros(4)

array([0., 0., 0., 0.])

In [11]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [15]:
np.linspace(0,10,11, dtype= int)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

##### Random Function

In [17]:
np.random.rand(5)

array([0.96979529, 0.91222915, 0.85980461, 0.65287301, 0.51250489])

In [18]:
np.random.rand(2,3)

array([[0.63707435, 0.64006667, 0.96380107],
       [0.54334418, 0.96515534, 0.38309145]])

In [19]:
np.random.randn(3,4)
# This is a uniform distribution curve

array([[ 0.37063974, -0.80242071,  0.73142471,  0.87581165],
       [-0.50342995,  0.29381785, -0.31329594, -0.01252002],
       [ 1.43640591, -1.48994306,  0.92502445,  0.28140264]])

In [20]:
np.random.randint(0,100,20)
#this gives random data between the initial and final numbers

array([32, 13, 70, 43, 91, 52,  6, 41, 50, 59, 83, 10, 24,  5, 96, 67, 39,
       70,  0, 33])

### To get fixed set of Random numbers 

In [21]:
np.random.seed(42)
np.random.randint(0,10,5)

array([6, 3, 7, 4, 6])

In [22]:
np.random.seed(42)
np.random.randint(0,10,6)

array([6, 3, 7, 4, 6, 9])

##### 42 is a random seed number. This will always give the same set of numbers 

In [23]:
arr= np.arange(0,20)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [25]:
arr.shape

(20,)

In [26]:
arr.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [27]:
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### min max

In [28]:
np.random.seed(42)
arr=np.random.randint(0,100,20)

In [29]:
arr

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74, 87, 99, 23,  2, 21, 52,  1,
       87, 29, 37])

In [30]:
arr.min()

1

In [31]:
arr.max()

99

In [32]:
arr.argmin()

16

In [33]:
arr.argmax()

11

# 2.Working on additional functions on Numpy

In [34]:
arr= np.arange(0,21,2)

In [35]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [36]:
arr[5]

10

In [37]:
arr[1:5]

array([2, 4, 6, 8])

In [38]:
arr[0:5]

array([0, 2, 4, 6, 8])

In [39]:
arr[:5] #the above cell and this gives the same result

array([0, 2, 4, 6, 8])

In [40]:
#this gives the array elements from the selected index till the last
arr[5:]

array([10, 12, 14, 16, 18, 20])

#### Broadcasting Reassignment

In [41]:
arr[0:5]=10
arr

array([10, 10, 10, 10, 10, 10, 12, 14, 16, 18, 20])

In [42]:
#Reassigning the original array
arr= np.arange(0,21,2)

In [43]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Impact of reassigning value on original array

In [44]:
slice_arr=arr[0:5]
slice_arr

array([0, 2, 4, 6, 8])

In [45]:
slice_arr[:]=5
slice_arr

array([5, 5, 5, 5, 5])

In [46]:
arr

array([ 5,  5,  5,  5,  5, 10, 12, 14, 16, 18, 20])

This is indicating that making a change in the slice_arr has impacted the original array

So we should be having a different set of operation to rectify this issue

##### Here, we will go with Copy method

In [47]:
#Reassigning the original array
arr= np.arange(0,21,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [48]:
arr_copy= arr.copy()
arr_copy

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [49]:
arr_copy[0:5]= 5
print("arr_copy:",arr_copy," : This is the assigned new array")
print("arr     :", arr," : This is the original array")

arr_copy: [ 5  5  5  5  5 10 12 14 16 18 20]  : This is the assigned new array
arr     : [ 0  2  4  6  8 10 12 14 16 18 20]  : This is the original array


Here we see that using the copy method there is no change in the original array

## 2- Dimensional Array

In [53]:
arr_2d= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [54]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arr_2d[0]

array([1, 2, 3])

In [59]:
arr_2d[:,1]

array([2, 5, 8])

In [61]:
#getting a sub section of the array
arr_2d[0:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [63]:
#Filtering

In [62]:

arr_2d[arr_2d>2]

array([3, 4, 5, 6, 7, 8, 9])