In [1]:
import numpy as np

### Statistics on Numpy

In [2]:
arr= np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Adding a specific number to each element on the array
print("arr   :",arr)
print("arr+10:",arr+10)

arr   : [0 1 2 3 4 5 6 7 8 9]
arr+10: [10 11 12 13 14 15 16 17 18 19]


In [4]:
print("arr   :",arr)
print("arr-10:",arr-10)

arr   : [0 1 2 3 4 5 6 7 8 9]
arr-10: [-10  -9  -8  -7  -6  -5  -4  -3  -2  -1]


In [5]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [6]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
#Division
arr/arr

/var/folders/_4/3d5m3y0n5lx55gjbss9ghngw0000gn/T/ipykernel_5209/2576009162.py:2: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [8]:
# we are getting nan in place of (0/0)

In [9]:
#mathematical functions

In [10]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [11]:
np.log(arr)

/var/folders/_4/3d5m3y0n5lx55gjbss9ghngw0000gn/T/ipykernel_5209/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [12]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [13]:
arr.sum()

45

In [14]:
np.sum(arr)

45

In [15]:
np.mean(arr)

4.5

In [16]:
np.max(arr)

9

In [17]:
np.min(arr)

0

In [18]:
arr.var()

8.25

In [19]:
arr.std()

2.8722813232690143

In [20]:
arr.shape[:]

(10,)

### Working with 2 D array

In [21]:
arr_2=np.arange(0,30).reshape(6,5)
arr_2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [22]:
arr_2.sum(axis=0)
# works on y axis

array([75, 81, 87, 93, 99])

In [23]:
arr_2.sum(axis=1)
#works on x axis

array([ 10,  35,  60,  85, 110, 135])

In [24]:
arr_2.sum()
#sum of all elements in the array

435

1. axis = 0 : This works across columns
2. axis = 1 : This works across rows
